lib/lotus/utils/hash.rb, lib/lotus/utils/string.rb, test/hash_test.rb, test/string_test.rb
Closes https://github.com/lotus/utils/issues/48
/cc @joneslee85 for review.
=> Ensure to return the right offending object if a missing method is called

lib/lotus/utils/attributes.rb, test/attributes_test.rb
=> Added `[]` as alias for get in attributes class

lib/lotus/interactor.rb, test/interactor_test.rb
=> Lotus::Interactor#error to return falsey value

lib/lotus/utils/attributes.rb, test/attributes_test.rb
Ref https://github.com/lotus/validations/issues/58
=> Ensure Attributes#to_h to force Hash values

lib/lotus/utils/string.rb, test/string_test.rb
Ref: https://github.com/lotus/helpers/issues/34
=> Introduced Utils::String#capitalize

lib/lotus/utils/kernel.rb
Noticed this whilst I was looking at how you do your coercions for Symbols.
Great work by the way :-)
Gav
=> Fix typo in documentation.

lib/lotus/utils/class_attribute.rb, lib/lotus/utils/duplicable.rb, lib/lotus/utils/hash.rb, test/class_attribute_test.rb, test/duplicable_test.rb
=> Introducing Utils::Duplicable for safe dup logic

CHANGELOG.md, Gemfile, lib/hanami/utils/kernel.rb, test/deprecation_test.rb, test/hash_test.rb, test/kernel_test.rb, test/string_test.rb
=> Drop support for MRI 2.0, 2.1 and Rubinius

lib/hanami/utils/inflector.rb, test/fixtures.rb
=> Fix inflections for "album"

lib/hanami/logger.rb, test/logger_test.rb
This is first step for all logger issues like https://github.com/hanami/hanami/issues/481.
/cc @jodosha
=> Allow logger to accept a device

.travis.yml, lib/hanami/utils/kernel.rb, test/escape_test.rb, test/kernel_test.rb
Removed jruby-9000 from travis and use only jruby-head.
Fixed tests related with BigDecimal and jruby-head
=> Fixed jruby head tests related with bigdecimal

lib/hanami/logger.rb, test/logger_test.rb
Reference to https://github.com/hanami/hanami/pull/530
=> Add level option to logger initializer

Gemfile, Rakefile, test/test_helper.rb
This is an experiment to rely only on Coveralls.
=> Remove simplecov

hanami-utils.gemspec, lib/hanami/utils/blank.rb, lib/hanami/utils/class_attribute.rb, test/escape_test.rb
Fixing a few Ruby warnings due to Rake 11.
---
/cc @hanami/core-team @hanami/contributors
=> Fix ruby warnings

test/basic_object_test.rb, test/string_test.rb
Hey guys, can you check if it's relevant? Just adding tests to:
```ruby
def respond_to_missing?(method_name, include_all)
::Kernel.raise ::NotImplementedError
end
```
and
```ruby
def singularize
self.class.new Inflector.singularize(self)
end
```
=> Added tests to BasicObject#respond_to_missing? and String#singularize

lib/hanami/utils/kernel.rb, test/kernel_test.rb
Reference https://github.com/hanami/utils/commit/57f6be767b917ff494476c25332e7cae501d904d
/cc @hanami/contributors @hanami/core-team
=> Add missing tests for Kernel#numeric? method

lib/hanami/logger.rb, test/logger_test.rb
Reference to https://github.com/hanami/hanami/issues/483
=> Introduce Base and JSON log formatters

Gemfile, lib/hanami/logger.rb, lib/hanami/utils/json.rb
/cc @hanami/contributors, @joneslee85 and @jodosha
=> Create wrapper for json module

lib/hanami/logger.rb, test/logger_test.rb
1. Don't display empty values
2. Display new line
/cc @jodosha and @joneslee85
=> Add end of line for default logger format

lib/hanami/logger.rb
Correct the examples for logger's tag
=> Correct logger tag example

lib/hanami/utils/basic_object.rb, test/basic_object_test.rb
This PR adds tests for `#class` and `#inspect` methods in `BasicObject`.
=> Add test for basic_object

lib/hanami/utils/basic_object.rb, test/basic_object_test.rb
Ref https://github.com/hanami/hanami/issues/629
=> Make Utils::BasicObject pretty printable

.travis.yml
=> Update jruby travis to 9.1.6.0

lib/hanami/interactor.rb, test/interactor_test.rb
=> Deprecate Hanami::Interactor::Result#failing?

lib/hanami/interactor.rb, lib/hanami/utils/hash.rb, test/hash_test.rb, test/interactor_test.rb
Fixes: https://github.com/hanami/utils/issues/159
/cc @jodosha
=> Hanami::Interactor Only symbolize keys of result payload

lib/hanami/utils/hash.rb, test/hash_test.rb
Fixes https://github.com/hanami/hanami/issues/653
=> Hanami::Utils::Hash#symbolize! now handles array

lib/hanami/utils/basic_object.rb
as seen at  http://www.rubydoc.info/gems/hanami-utils/Hanami/Utils/BasicObject#pretty_print-instance_method
=> Copyedit doc for Hanami::Utils::BasicObject#pretty_print

lib/hanami/interactor.rb, test/interactor_test.rb
Fixes #188 
cc @jodosha @hanami/issues
=> interactor: Don't transform objects responding to #to_hash to a hash

lib/hanami/interactor.rb
It's now just `failure?`.
Clean up for #194
=> Remove references to removed `failing?` method

hanami-utils.gemspec, lib/hanami/logger.rb, test/class_attribute_test.rb, test/interactor_test.rb, test/isolation/reload_test.rb
=> Clean up code according to rubocop 0.48

hanami-utils.gemspec, lib/hanami/utils/hash.rb, spec/unit/hanami/utils/hash_spec.rb
Partial implementation of this proposal: https://discourse.hanamirb.org/t/transform-utils-string-and-utils-hash-to-modules/336
Ref hanami/model#394
Ref hanami/model#395
=> Introduce `Utils::Hash.symbolize` and `.deep_symbolize`

lib/hanami/utils/string.rb, test/string_test.rb
=> Fix wrong classify behavior if the string is already classified

lib/hanami/utils/hash.rb, spec/unit/hanami/utils/hash_spec.rb
Test by @badeball , see https://github.com/hanami/utils/pull/216
=> Don't mutate input hash unless necessary

lib/hanami/utils/inflector.rb
Fixes https://github.com/hanami/utils/issues/217
/cc @hanami/core
=> Add 'phase' word to rules for singulars

lib/hanami/utils/string.rb, spec/unit/hanami/utils/string_spec.rb
Make class methods for the following instance methods:
* `.titleize`
* `.capitalize`
* `.classify`
* `.underscore`
* `.dasherize`
* `.demodulize`
* `.namespace`
* `.pluralize`
* `.singularize`
* `.rsub`
=> Change String instance methods to class methods

lib/hanami/utils/inflector.rb, spec/support/fixtures/fixtures.rb
Fix singular of `releases`, `release` instead of `releas`.
=> inflector: Fix singular of "releases"

README.md, lib/hanami/logger/formatter.rb, lib/hanami/utils/query_string.rb, spec/unit/hanami/logger_spec.rb, spec/unit/hanami/utils/query_string_spec.rb
=> Fix logger Hash formatting

lib/hanami/utils/files.rb, spec/unit/hanami/utils/files_spec.rb
Fixes #266 
I decided to start helping with issues ❤️ Also I love to remove code 😄
=> remove Utils::File.rewrite

lib/hanami/utils/class.rb, spec/unit/hanami/utils/class_spec.rb
https://github.com/hanami/utils/issues/262
=> Deprecate Utils::Class.load_from_pattern!

lib/hanami/utils/files.rb, spec/unit/hanami/utils/files_spec.rb
Added two now methods:
* inject_line_after_last
* inject_line_before_last
Needed for https://github.com/hanami/hanami/pull/883
=> Add methods for injection before/after last target

lib/hanami/result.rb, spec/unit/hanami/result_spec.rb
Required by: https://github.com/hanami/validations/pull/141
=> [Experimental] Hanami::Result

.circleci/config.yml, .travis.yml, lib/hanami/utils/class.rb, lib/hanami/utils/string.rb, spec/support/silence_deprecations.rb, spec/unit/hanami/utils/blank_spec.rb, spec/unit/hanami/utils/duplicable_spec.rb, spec/unit/hanami/utils/escape_spec.rb, spec/unit/hanami/utils/inflector_spec.rb, spec/unit/hanami/utils/kernel_spec.rb, spec/unit/hanami/utils/string_spec.rb
Ref https://github.com/hanami/utils/issues/259
=> Deprecate Utils::String instance methods

lib/hanami/utils/class_attribute.rb, lib/hanami/utils/class_attribute/attributes.rb, spec/unit/hanami/utils/class_attribute/attributes_spec.rb, spec/unit/hanami/utils/class_attribute_spec.rb
=> Make `Utils::ClassAttribute` to use `Concurrent::Map`

lib/hanami/middleware.rb, spec/unit/hanami/middleware_spec.rb
Added `Hanami::Middleware` namespace as commented in https://github.com/hanami/router/pull/176#discussion_r207853832
=> add Hanami::Middleware module

lib/hanami/utils/string.rb, spec/unit/hanami/utils/string_spec.rb
Same as https://github.com/hanami/utils/pull/397 just for main branch.
=> Replace period in underscored string

.yardopts, Gemfile, lib/hanami/middleware.rb, lib/hanami/utils/class.rb, lib/hanami/utils/json.rb, lib/hanami/utils/shell_color.rb, lib/hanami/utils/version.rb
The changes needed here were fairly minor. I just filled in a couple of gaps and removed a now-unused method.
=> Update API docs for 2.0.0
