lib/lotus/utils/callbacks.rb, test/callbacks_test.rb
This PR introduces `Chain#append` and `Chain#prepend` as discussed in lotus/controller#76.
The final version is the result of several iterations and benchmarks. I kept all the changes in the repo, along with the benchmarks, so that we can analyse the different implementations.
I'm open to feedback.
The last step is to reintroduce `Chain#add`. However, I have a question. How would you love the method to be tested?
Generally, I test delegation using a stub library. Does it make sense to "clone" all the tests we have for `prepend`? May be no. I think that using a single, generic test (like passing calling the method twice, with a bunch of different versions and checking the result) is sufficient to cover most of the cases.
=> Chain append/prepend

lib/lotus/utils/callbacks.rb, test/callbacks_test.rb
Ditto.
---
Now that we have specular API: `#append` and `#prepend` we can get rid of `#add`, which is redundant and ambiguous for the new semantic.
Ref #52
=> Deprecated Lotus::Utils::Callbacks::Chain#add in favor of #append

.travis.yml
JRuby fails due to an encoding error, see: jruby/jruby#2581
=> Simplify travis (jruby-head runs 2.2 compatible by default)

lib/lotus/utils/string.rb, test/string_test.rb
`Utils::String#titleize`
```ruby
require 'lotus/utils/string'
string = Lotus::Utils::String.new 'lotus utils'
string.titleize # => "Lotus Utils"
string = Lotus::Utils::String.new 'lotus-utils'
string.titleize # => "Lotus Utils"
string = Lotus::Utils::String.new 'LotusUtils'
string.titleize # => "Lotus Utils"
```
This is a supporting feature for Lotus::Helpers' form helper.
```erb
<%=
form_for(:book, routes.books_path) do
label :extended_title
end
%>
```
That `label` accepts a symbol that should be titleized to become:
```html
<label for="book-extended-title">Extended Title</label>
```
=> Introduced Utils::String#titleize

lib/lotus/utils/string.rb, test/string_test.rb
`Utils::String#dasherize`
```ruby
require 'lotus/utils/string'
string = Lotus::Utils::String.new 'lotus utils'
string.dasherize # => "lotus-utils"
string = Lotus::Utils::String.new 'lotus_utils'
string.dasherize # => "lotus-utils"
string = Lotus::Utils::String.new 'LotusUtils'
string.dasherize # => "lotus-utils"
```
This is a supporting feature for Lotus::Helpers' form helper.
```erb
<%=
form_for(:book, routes.books_path) do
text_field :extended_title
end
%>
```
That `text_field` accepts a symbol which produces HTML attributes. This new `Utils::String` functionality will be used to produce `id`:
```html
<input type="text" name="book[extended_title]" id="book-extended-title" value="">
```
=> Introduced Utils::String#dasherize

lib/lotus/utils/string.rb, test/string_test.rb
Made #classify able to handle namespaces delimited by '/' (e.g "lotus/router/mapping".classify # "Lotus::Router::Mapping)
=> Namespace support for #classify

lib/lotus/utils/inflector.rb, lib/lotus/utils/string.rb, test/fixtures.rb, test/inflector_test.rb
Introduce singularization for strings.
It adds a new public API method: Utils::String#singularize, which returns a new singularized instance of the same type.
```ruby
string = Lotus::Utils::String.new("flowers")
string.singularize       # => "flower"
string.singularize.class # => Lotus::Utils::String
```
The implementation is delegated to a new module: Lotus::Utils::Inflector. It exposes .singularize which works with Ruby's String.
```ruby
Lotus::Utils::Inflector.singularize("flowers")       # => "flower"
Lotus::Utils::Inflector.singularize("flowers").class # => String
```
Sigunlaritazion is idempotent.
```ruby
Lotus::Utils::Inflector.singularize(
Lotus::Utils::Inflector.singularize("user")
) # => "user"
```
It respects the case:
```ruby
Lotus::Utils::Inflector.singularize("Applications") …
```
=> Singularize [WIP]

lib/lotus/utils/attributes.rb, test/attributes_test.rb
Only convert `::Hash`, `Utils::Hash` and `Lotus::Validations::NestedAttributes`.
Ref https://github.com/lotus/validations/issues/58
=> When coerce Utils::Attributes to Hash don't rely on #to_h of the single values

lib/lotus/interactor.rb
Just two module includes I suspect are missing in the examples for Lotus::Interactor.
=> Add missing Lotus::Interactor include in examples

lib/lotus/utils/kernel.rb, test/kernel_test.rb
I was struck by a `TypeError` with no information about what went wrong:
```
TypeError: can't convert into Integer
```
The backtrace led me nowhere as this was all framework code. The last code that belonged to me was the call to `Repository#create`. After that, it was all library code. See https://gist.github.com/francois/283f9ee23d268b69aa60 for a sample backtrace.
Now, I get a much more useful error message:
```
TypeError: can't convert #<Date: 2015-04-20 ((2457133j,0s,0n),+0s,2299161j)> into Integer
```
=> Make TypeError messages even more useful

lib/lotus/interactor.rb, test/interactor_test.rb
This is a proposal for a few `Lotus::Interactor` improvements.
:warning: **The following change isn't backward compatible** :warning: 
--
Until now all the instance variables from an interactor were automatically exposed into the returning value of `#call`, which is an instance of `Lotus::Interactor::Result`.
```ruby
class Signup
include Lotus::Interactor
def initialize(params)
@params = params
@user = User.new(params.fetch(:user))
end
def call
end
end
result = Signup.new(user: { name: "Luca" }).call
result.user   # => #<User:0x007fa311105778 @id=1 @name="Luca">
result.params # => { :user=>{:name=>"Luca"} }
```
```ruby
class Signup
include Lotus::Interactor
expose :user
def initialize(params)
@params = params
@user = User.new(params.fetch(:user))
end
end
result = Signup.new(user: { name: …
```
=> Interactor improvements

lib/lotus/utils/path_prefix.rb, test/path_prefix_test.rb
This is an issue i tracked back to from the router.
So given this prefix:
```
prefix = Lotus::Utils::PathPrefix.new('fruits')
```
when joined with the same string
```
prefix.join('fruits') # => /fruits
```
will get rid of one of them only keeping the above `/fruits` instead of `/fruits/fruits`
Obviously that shouldn't be the case because we should be able to have paths such as `/fruits/fruits/fruits/fruits` if we wanted to.
Basically the issue is because PathPrefix uses Lotus::Kernel.Array which calls .uniq! on itself and removes any duplicate items.
I was able to fix the issue by using the standard array for the relative_join + calling chomp("/") on the result of the join to make some tests happy. 
I'm not entirely sold on this solution because it seems to me that even though this fixed …
=> Bug in PathPrefix's relative_join

lib/lotus/utils/escape.rb, test/escape_test.rb
I defined following code in controller.
```ruby
module Web::Controllers::Home
class Index
def call(params)
@tag = params[:tag]
end
end
end
```
Then I received Encoding::UndefinedConversionError in template from method self.encode in Lotus::Utils when tag contain cyrillic symbols. For some reason params[:tag] have ASCII-8BIT encoding.
So, I added quick fix for that issue.
=> Fix Encoding::UndefinedConversionError in encode method.

lib/lotus/utils/string.rb, test/string_test.rb
It replaces rightmost occurence of given pattern and replaces with given replacement.
```ruby
require 'lotus/utils/string'
string = Lotus::Utils::String.new('authors/books/index')
string.rsub("/", "#") # => "authors/books#index"
```
This feature supports https://github.com/lotus/router/pull/76
/cc @lotus/core-team
=> Introducing Lotus::Utils::String#rsub

lib/lotus/utils/string.rb
I used stackprof gem and this code:
``` ruby
100_000.times { Lotus::Utils::String.new('lotus_utils/test').classify }
```
```
==================================
Mode: object(1)
Samples: 3500005 (0.00% miss rate)
GC: 0 (0.00%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
3300005  (94.3%)     1600004  (45.7%)     Lotus::Utils::String#classify
900000  (25.7%)      900000  (25.7%)     Lotus::Utils::String#method_missing
800001  (22.9%)      800001  (22.9%)     Lotus::Utils::String#split
```
```
==================================
Mode: object(1)
Samples: 3000005 (0.00% miss rate)
GC: 0 (0.00%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
2800005  (93.3%)     1100004  (36.7%)     Lotus::Utils::String#classify
900000  (30.0%) …
```
=> Reduce allocations for String#classify method

CHANGELOG.md, lib/lotus/utils/class.rb, test/class_test.rb
It was deprecated by `v0.3.1` (a46aecf6bfa620c7d0a578768ad7b7fe5253cef5)
=> Remove pattern support for Lotus::Utils::Class#load!

lib/hanami/utils/escape.rb, test/escape_test.rb
In `0.5.0` you can directly escape (`encode`) a `Date` object. In `0.6.0` +, you have to manually call `.to_s` first. This partially reverts [this commit](https://github.com/hanami/utils/commit/9221338890dc9e7361509fbfc03d14bf94616ec1).
In the `rescue Encoding::UndefinedConversionError` block, I haven't added calling this `.to_s` call. Should we add it there too? I'm not really sure how that code works.
I've added regression tests for:
- Time
- Date
- DateTime
Are there any other Classes we should test for?
Closes #113, @davydovanton !
=> Class `.to_s` on objects when encoding them

lib/hanami/utils/escape.rb
Since Ruby 2.0.0, `String#chars` returns an array instead of an enumerator. Passing a block is deprecated.
ref: https://github.com/ruby/ruby/commit/3f9b0936aa846bdf6984019ca40bc629fe05d929
=> do not pass the block to `String#chars`

lib/hanami/utils/hash.rb, test/hash_test.rb
Hi,
This pull request adds support for `symbolize!` and `stringify!`with nested `Hanami::Utils::Hash` as values.
I'm not sure if there is a reason not to do this, or maybe there are a better way of implementing this. For instance: [ActiveSupport::TimeWithZone](https://github.com/rails/rails/blob/0e528b626cb164153dea45b4528888ef663cad83/activesupport/lib/active_support/time_with_zone.rb#L334) do override `is_a?` so it returns `true` when asked if `time_with_zone.is_a? Time`. Some tests broke when went this way with `Utils::Hash`.
=> Utils::Hash #symbolize! and #stringify! supporst nested Utils::Hash values

lib/hanami/utils/string.rb, test/string_test.rb
- Adding `underscore` before splitting word so that `capitalize` does not make `p` become lowercase.
Fix #119
=> [b] Utils::String#classify "AwesomeProject" => "Awesomeproject"

lib/hanami/utils/escape.rb
Here are the warnings:
```
../lib/hanami/utils/escape.rb:514:in `url': warning: URI.extract is obsolete
../lib/hanami/utils/escape.rb:515:in `url': warning: URI.unescape is obsolete
```
This solves the problems reported in #127 and #128.
=> Removing warnings for URI.extract and URI.unescape because these methods are now obsolete

test/logger_test.rb
Fixed #132.
I found that `'custom stream file system'` group have a `before` callback [on the top of group][callback]. This callback create new `tmp` path and use `stream` value for this.
My patch fixed naming problems, also I removed unnecessary test and completed test for file permission.
Thanks @rogeriozambon for his [bash code][bashcode]. On my local machine all works fine:
/cc @hanami/core-team @hanami/contributors 
[callback]: https://github.com/hanami/utils/blob/master/test/logger_test.rb#L73-L75
[bashcode]: https://github.com/hanami/utils/issues/132#issuecomment-200177326
=> Fix broken tests for logger class

test/string_test.rb
Improve the present of `string_test`, use single quote (') whenever possible
=> Improve single quote consistency for string_test

lib/hanami/utils/attributes.rb, test/attributes_test.rb
Address https://github.com/hanami/controller/issues/70 by making `Hanami::Utils::Attribute#get` return `Hanami::Utils::Attributes` for hash-like attribute values.
=> Allow deep indifferent access on Hanami::Utils::Attributes

lib/hanami/utils/class.rb, test/class_test.rb
Fixes https://github.com/hanami/utils/issues/151
Honestly i'm not sure about the side-effects of this to current hanami. But I think the behavior described in issue 151 is a bug.
=> Making sure that only current namespace is checked when loading classes.

lib/hanami/interactor.rb, test/interactor_test.rb
Example:
```
module Web::Controllers::Projects
class Create
include Web::Action
params do
param :project do
param :name, presence: true
end
end
def call(params)
return unless params.valid?
create_project = CreateProject.new(params[:project]).call
return if create_project.failure?
redirect_to routes.projects_path
end
end
end
```
=> Add methods #successful? and #failing? to Interactor

lib/hanami/utils/hash.rb, test/fixtures.rb, test/hash_test.rb
Enhanced behavior for:
* `#symbolize!`
* `#stringify!`
* `#to_h`
=> Make Utils::Hash compatible w/ objects that respond to `#to_hash`

lib/hanami/utils.rb, test/fixtures/file_list/a.rb, test/fixtures/file_list/aa.rb, test/fixtures/file_list/ab.rb, test/fixtures/file_list/nested/c.rb, test/isolation/require/with_absolute_path_test.rb, test/isolation/require/with_file_separator_test.rb, test/isolation/require/with_recursive_pattern_test.rb, test/isolation/require/with_relative_path_test.rb
A cross-platform, ordered, recursive way to require Ruby files.
=> Introducing `Hanami::Utils.require!`

CHANGELOG.md, lib/hanami/utils/json.rb, lib/hanami/utils/version.rb, test/isolation/json/json_test.rb, test/isolation/json/multi_json_test.rb, test/version_test.rb
Introduced `Hanami::Utils::Json.parse` for safe JSON parsing.
Deprecate `Hanami::Utils::Json.load` in favor of `.parse`.
Introduced `Hanami::Utils::Json.generate` for safer JSON generation.
Deprecate `Hanami::Utils::Json.dump` in favor of `.generate`.
---
Closes #169 
/cc @AlfonsoUceda @beauby
=> Introduced `Hanami::Utils::Json.parse` for safe JSON parsing.

.travis.yml
So we can get updates in Gitter when builds fail.
cc @AlfonsoUceda
=> Add Gitter webhook to Travis config

.rubocop.yml
Don't require OrderedGems or EmptyMethods to be on same line (new rules introduced in latest version of Rubocop).
=> Fix (rubocop) build

lib/hanami/utils/inflector.rb, test/fixtures.rb
Plural rules with adding -s instead of changing ending to -ina are considered to be correct (i.e. "stamens" instead of "stamina") and do not create false plural forms of common English words, such as "kitten". They are still correctly singularized, though.
See: https://github.com/hanami/utils/issues/173
=> Pluralize -en to -ens instead of -ina

lib/hanami/logger.rb
update deprecated method `dump` to `generate`
=> Remove deprecation warning for logger json format output

lib/hanami/logger.rb, test/logger_test.rb, test/test_helper.rb
Talking with @jodosha I saw this example log for default formatter in hanami logger:
```
app=hanami.model severity=INFO time=2017-01-03 17:17:17 UTC message=(0.000260s) SELECT `id`, `name`, `created_at`, `updated_at` FROM `authors` WHERE (`id` IN (1)) ORDER BY `authors`.`id`
```
This kind of log, will break with integrations like logstash, if your value has spaces, then it should be wrapped between quotes. (I'm using single quotes).
For time, I'm using RFC 3339 in UTC without spaces.
The result of the previous log would be:
```
app=hanami.model severity=INFO time=2017-01-03T17:17:17+00:00 message='(0.000260s) SELECT `id`, `name`, `created_at`, `updated_at` FROM `authors` WHERE (`id` IN (1)) ORDER BY `authors`.`id`'
```
cc @hanami/contributors @hanami/core
=> Improve logger

.rubocop.yml, lib/hanami/utils.rb, test/isolation/reload_test.rb
This is a proposal to add an API to recursively reload Ruby code for a given directory.
This is related to https://github.com/hanami/hanami/issues/702.
The way code reloading working for Hanami 0.9 is to use Shotgun as a mechanism to reload the code.
Shotgun works fine for all the Rack applications in a project, but not for other code outside of them.
For a Hanami project `apps/` gets reloaded, but `lib/` doesn't.
This PR introduces a mechanism to force code reloading via `Kernel.load`. When a file was already required, in order to reload it's content, loading it will refresh the code the Ruby VM.
**Please note** that this new `Hanami::Utils` feature will be used in Hanami projects only for `lib/`.
/cc @hanami/ecosystem @hanami/issues for review.
=> `Hanami::Utils.reload!`

lib/hanami/logger.rb, test/logger_test.rb
This proposal introduces a small change in the logger. When we pass a Hash, it should print all the key/value pairs instead of wrapping them into `:message` key.
```ruby
logger.info(http: "HTTP/1.1", verb: "GET")
```
```ruby
logger.info(http: "HTTP/1.1", verb: "GET")
```
```ruby
logger.info(http: "HTTP/1.1", verb: "GET")
```
```ruby
logger.info(http: "HTTP/1.1", verb: "GET")
```
---
/cc @AlfonsoUceda @hanami/issues @hanami/ecosystem for review 👍
=> Logger hash message

lib/hanami/utils/blank.rb, test/blank_test.rb
I think it will be helpful to have the antonym for `.blank?` method instead of using `!Hanami::Utils::Blank.blank?(value)`.
WDYT?
/cc @hanami/core @hanami/ecosystem
=> Introduce ::filled? method

.rubocop.yml, lib/hanami/logger.rb, lib/hanami/utils/blank.rb, lib/hanami/utils/callbacks.rb, lib/hanami/utils/class_attribute.rb, lib/hanami/utils/deprecation.rb, lib/hanami/utils/escape.rb, lib/hanami/utils/inflector.rb, lib/hanami/utils/kernel.rb
```
➜ bundle exec yardoc --no-cache --no-save --protected --private --no-api private --markup markdown lib
Files:          21
Modules:        12 (    0 undocumented)
Classes:        13 (    0 undocumented)
Constants:       2 (    0 undocumented)
Attributes:      1 (    0 undocumented)
Methods:        97 (    0 undocumented)
100.00% documented
```
Please note that the command above will be used by our upcoming API docs website: https://github.com/hanami/docs
=> API docs cleanup

CHANGELOG.md, lib/hanami/logger.rb, test/logger_test.rb, test/test_helper.rb
`Hanami::Logger` uses `STDOUT` as default stream. This isn't the correct stream to use.
By looking at the Ruby [core documentation](http://ruby-doc.org/core/doc/globals_rdoc.html) there is a difference between `STDOUT` and `$stdout`:
> `STDOUT`
> The standard output. The default value for `$stdout`.
> `$stdout`
> The current standard input.
The first represents the **initial** value for _standard output_, assigned when a program is started. The latter is the **current** standard output. That means a program can reassign `$stdout` for some reason and expect the rest of the system to work.
Ruby core itself uses `$stdout` and not `STDOUT`. `Kernel#puts` (aka implicit `puts`), report this comment in its [API doc](http://ruby-doc.org/core/Kernel.html#method-i-puts):
> Equivalent to
> …
=> Use `$stdout` instead of `STDOUT` as default stream for `Hanami::Logger`

lib/hanami/interactor.rb, lib/hanami/utils/callbacks.rb
I noticed these comments were out-of-date, with the `hanami-model` change to use instance methods instead of class methods.
=> Change repository class methods to instance methods

.travis.yml, lib/hanami/logger.rb, test/logger_test.rb
Allow to pass arbitrary arguments to the logger, so they can be forwarded to the superclass.
```ruby
require 'hanami/logger'
logger = Hanami::Logger.new('bookshelf', 'daily', stream: 'development.log')
```
```ruby
require 'hanami/logger'
logger = Hanami::Logger.new('bookshelf', 10, 1024000, stream: 'development.log')
```
See https://ruby-doc.org/stdlib/libdoc/logger/rdoc/Logger.html#class-Logger-label-How+to+create+a+logger
---
Closes #201 /cc @sebastjan-hribar and @hanami/core for review.
=> Logger arguments

lib/hanami/utils/hash.rb, spec/unit/hanami/utils/hash_spec.rb
As cleanup for https://github.com/hanami/model/pull/395, we need to replace in `Hanami::Entity` `Hanami::Utils::Hash#deep_symbolize!` with `Hanami::Utils::Hash.deep_symbolize`.
The first method returns an instance of `Hanami::Utils::Hash` which respond to `#deep_dup`. The new `.deep_symbolize` returns a `::Hash`, which doesn't have `#deep_dup`. Here's the reason for this PR.
Please note, that after the merge of https://github.com/hanami/model/pull/395 `hanami-model` `master` branch is in a "dirty" state, as it requires an additional PR to reach the wanted behavior.
---
This proposal continues the idea introduced by #210 of moving `Utils::Hash` transformations away from instance methods and to port all the existing ones to class methods.
/cc @hanami/core
=> Implement Utils::Hash.deep_dup

lib/hanami/interactor.rb
Update documentation for the persisting of the repository to use the
create method instead of the persist method due to the persist method
not existing for quite some time.
The example could confuse a user trying to implement the pattern causing
false issues being posted or time loss.
Relates to issue #213
=> Update Documentation To Not Use persist Method

lib/hanami/interactor.rb, spec/unit/hanami/interactor_spec.rb
ATM, the parameters for the execution are send at the initialization of the instance. This behavior poses 2 main issues:
* it is really hard to make Dependency Injections
* there is no way to reuse an Interactor instance with other parameters
This PR aims at introducing a new format that would solve the previously mentioned issues, all the while still supporting the previous format.
New format example:
```ruby
class Hello
include Hanami::Interactor
expose :hello
def call(target:)
@hello = "Hello #{target}"
end
private
def valid?(target:)
!target == 'me'
end
end
hello = Hello.new
hello.call(target: 'world') # => valid?: true, hello: 'Hello world'
hello.call(target: 'me') # => valid?: false
```
TODO:
=> Introduce new interactor format

.rubocop.yml, lib/hanami/utils/files.rb, spec/support/files.rb, spec/unit/hanami/utils/files_spec.rb
This is a set of helpers that we were using since long time in `hanami` test suite.
With the new CLI for `hanami`, based on `hanami-cli`, we needed to extract that helpers from the test suite and promote it as production code.
Ref https://github.com/hanami/hanami/pull/808
=> Introduce `Utils::Files`

CHANGELOG.md, hanami-utils.gemspec, lib/hanami/utils/string.rb, spec/unit/hanami/utils/string_spec.rb
Apply the given transformation(s) to `input`
It performs a pipeline of transformations, by applying the given functions from `Hanami::Utils::String` and `::String`
The transformations are applied with the given order.
It doesn't mutate the input, unless a developer uses destructive methods from `::String`
```ruby
require "hanami/utils/string"
Hanami::Utils::String.transform("hanami/utils", :underscore, :classify)
Hanami::Utils::String.transform("Hanami", :downcase, :reverse)
Hanami::Utils::String.transform("Hanami::Utils::String", [:gsub, /[aeiouy]/, "*"], :demodulize)
Hanami::Utils::String.transform("Hanami", ->(s) { s.upcase })
```
In our codebase we have chained transformations like:
```ruby
Hanami::Utils::String.new(string).underscore.classify
```
or
```ruby …
```
=> Introduce `Hanami::Utils::String.transform`

lib/hanami/utils/inflector.rb, spec/support/fixtures/fixtures.rb
I encountered an error with the singularisation rule of `exercises`, so I fixed it by adding an exception and a test for it.
=> Fix the singular of exercises (exercise rather than exercis).

lib/hanami/logger.rb, spec/unit/hanami/logger_spec.rb
I've noticed when you create a hanami app and add a stream in your development logger, for example a path 'log/development.log', it will fails because log folder isn't created. IMO logger should be in charge of create the path.
What do you think?
=> logger: creates folder when doesn't exist

lib/hanami/utils/path_prefix.rb
```ruby
require 'hanami/utils/path_prefix'
require 'memory_profiler'
path_prefix = Hanami::Utils::PathPrefix.new '_posts'
MemoryProfiler.report{ 10_000.times { path_prefix.relative_join('new', '_').to_s } }.pretty_print(to_file: 'path_to_your_log_file')
```
```
Total allocated: 31580080 bytes (240002 objects)
Total retained:  0 bytes (0 objects)
allocated memory by gem
-----------------------------------
30780080  utils/lib
800000  other
allocated memory by file
-----------------------------------
30780080  /Users/anton/work/repositories/lotus/utils/lib/hanami/utils/path_prefix.rb
800000  (irb)
allocated memory by location
-----------------------------------
16200040  /Users/anton/work/repositories/lotus/utils/lib/hanami/utils/path_prefix.rb:135
11300040 …
```
=> Reduce memory allocation for PathPrefix#relative!

CHANGELOG.md, lib/hanami/utils/basic_object.rb, spec/unit/hanami/utils/basic_object_spec.rb
=> Make `Hanami::Utils::BasicObject` to be fully compatible with Ruby's `pp` and to be inspected by Pry

lib/hanami/utils/hash.rb, spec/unit/hanami/utils/hash_spec.rb
The feature:
```ruby
require "hanami/utils/hash"
require "ostruct"
class Data < OpenStruct
def to_hash
to_h
end
end
input = Data.new("foo" => "bar", baz => [Data.new(hello: "world")])
Hanami::Utils::Hash.deep_serialize(input)
```
---
This feature is needed to make `hanami-controller`'s `BaseParams` and `Params` to be deep serialized into `Hash`, so they can be used directly into `hanami-model` associations.
```ruby
class AuthorRepository < Hanami::Repository
associations do
has_many :books
end
def create_with_books(data)
assoc(:books).create(data)
end
end
```
```ruby
module Web::Controllers::Authors
class Create
include Web::Action
def call(params)
AuthorRepository.new.create_with_books(params)
AuthorRepository.new.create_with_books(params.to_hash)
end
end
end
```
With this PR we can …
=> Introduce `Utils::Hash.deep_serialize` to recursively serialize input into `::Hash`

lib/hanami/interactor.rb, spec/unit/hanami/interactor_spec.rb
Hi, I'm using hanami for my new project, and I love it. Thank you for a cool framework.
I've noticed that new interactor interface (from 1.1) cannot handle some argument patterns.
I propose a solution to handle such cases.
**case 1: no keyword arguments**
In this case, the actual arguments passed to #call is `['foo', 'bar', {}]`
This can be avoided to change #call args to `call(foo, bar, *)` but i think it is not cool 🤔 
```foo_interactor.rb
class FooInteractor
include Hanami::Interactor
def call(foo, bar)
end
end
```
```
[3] pry(main)> interactor = FooInteractor.new
=> #<FooInteractor:0x007f9d2797ef98>
[4] pry(main)> interactor.call('foo', 'bar')
ArgumentError: wrong number of arguments (given 3, expected 2)
from (pry):4:in `call'
```
**case 2: no keyword arguments and an argument with …
=> Modify new interactor's argument list to handle some cases

lib/hanami/utils/hash.rb, spec/unit/hanami/utils/hash_spec.rb
Introduces a new utility method: `Hanami::Utils::Hash.deep_stringify` to recursively stringify hashes.
```ruby
require "hanami/utils/hash"
hash = Hanami::Utils::Hash.deep_stringify(a: { b: { c: { d: [:e] }}})
hash.class
```
---
Closes #241 
Ref #243
=> Introduce Utils::Hash.deep_stringify

.travis.yml, lib/hanami/utils/hash.rb, lib/hanami/utils/kernel.rb, spec/unit/hanami/utils/duplicable_spec.rb, spec/unit/hanami/utils/hash_spec.rb, spec/unit/hanami/utils/kernel_spec.rb
This PR also removes the usage of `BigDecimal.new` in favor of `Kernel.BigDecimal`, as suggested by Ruby 2.5.0 warnings.
=> Official support for Ruby 2.5.0

lib/hanami/utils/string.rb
While pairing programming with @oana-sipos today, I noticed some of the API docs for `Hanami::Utils::String` were unclear or wrong.
There was some usage of `String`, which wasn't clear in this context.
Now, all are either `::String` or `Hanami::Utils::String`
I also cleaned up a couple other API docs that I noticed were wrong (`nil` was given as a possible return value, but I don't think that's accurate, and `scan`'s comment didn't explain it).
=> Fix String API docs

lib/hanami/utils/files.rb, spec/unit/hanami/utils/files_spec.rb
The comments for `Hanami::Utils::Files.write` says:
```
```
The method did not do this. Instead, [it replaced the beginning of the file](https://github.com/hanami/cli/issues/22). 
Fixes part of https://github.com/hanami/hanami/issues/855.
=> Fix Files.write behavior

lib/hanami/logger.rb, lib/hanami/logger/colorizer.rb, spec/unit/hanami/logger_spec.rb
Colorize logger severity with the following scheme:
* UNKNOWN => blue
* DEBUG => cyan
* INFO => magenta
* WARN => yellow
* ERROR, FATAL => red
=> Colorize logger severity

spec/unit/hanami/utils/kernel_spec.rb
During ./script/ci warning was shown:
/home/wolf/devel/hanami-utils/spec/unit/hanami/utils/kernel_spec.rb:1494: warning: constant ::Fixnum is deprecated
This change fixes it.
=> Fixnum is deprecated and warning was showing

.circleci/config.yml, .jrubyrc, .travis.yml, Gemfile, README.md, Rakefile, script/ci, spec/support/coverage.rb, spec/support/isolation_spec_helper.rb
Let's try these services for a week.
This PR:
=> Update settings for code quality services

.circleci/config.yml, script/ci
We had no control over the machines/images used for our CI. Even with the recent introduction of CircleCI, they removed `circleci/jruby:9.1.1.13` in favor of `circleci/jruby:9.1-jdk`.
This removal or minor updates to the images can potentially cause sudden CI failures.
---
In order to take control and fix this problem, we can use our own Docker images for CI. See https://github.com/hanami/docker-ci-images
From now on, no sudden image changes that can break the builds. If a new version of Ruby is out, we need to update our own images and restart a build.
=> Custom CI images

lib/hanami/utils/inflector.rb, spec/support/fixtures/fixtures.rb
Fixes #289 
---
Note for the reviewers: this is a bug fix. Bug fixes usually targets `master` as base branch. But because I want to release this fix with `v1.3.0.beta1` (out in two days), here's why we have this unusual PR.
=> Fix pluralization of 'fee'

lib/hanami/utils.rb
Simple as that. This was passing `bundle exec rake` but `bundle exec rspec spec/unit/hanami/utils/string_spec.rb` would die with a `NameError`, as described in #299.
Fixes #299
=> Fix #299 by adding require to lib/hanami/utils.rb

lib/hanami/utils/query_string.rb, spec/unit/hanami/logger_spec.rb, spec/unit/hanami/utils/query_string_spec.rb
Fixes #295
```
q = {foo: "1", bar: nil, baz: "hello"}
Hanami::Logger.new.debug(q)
[Hanami] [DEBUG] [2018-09-17 10:07:24 +0200] foo=25,bar=,baz=What is this?
```
I suggest to use json formatter instead of default formatter  because it supports deep nested hashes.
=> logger: fix default formatter for hashes

spec/unit/hanami/utils/string_spec.rb
The motivation behind this is the following issue https://github.com/oracle/truffleruby/issues/1467 in Truffleruby issues. They already fixes on their side.
As mentioned @eregon in his comment https://github.com/oracle/truffleruby/issues/1467#issuecomment-438354081 this improving portability of the library than making checking based on `RUBY_ENGINE`
=> Agnostic ArgumentError's message check in utils/string_spec.rb

lib/hanami/utils/file_list.rb, spec/unit/hanami/utils/file_list_spec.rb
```ruby
require "hanami/utils/file_list"
Hanami::Utils::FileList["spec/support/fixtures/file_list/*.rb"]
"spec/support/fixtures/file_list/a.rb",
"spec/support/fixtures/file_list/aa.rb",
"spec/support/fixtures/file_list/ab.rb"
]
```
```ruby
require "hanami/utils/file_list"
Hanami::Utils::FileList["spec", "support", "fixtures", "file_list", "*.rb"]
"spec/support/fixtures/file_list/a.rb",
"spec/support/fixtures/file_list/aa.rb",
"spec/support/fixtures/file_list/ab.rb"
]
```
From the work I'm doing on `hanami`, I want to support this usage:
```ruby
Hanami::Utils::FileList[c.root, "apps", app.to_s, "actions", "**", "*.rb"].each do |path|
end
```
=> Allow `Hanami::Utils::FileList` to accept multiple tokens

.drone.yml, Gemfile, lib/hanami/utils/basic_object.rb, lib/hanami/utils/kernel.rb, script/test, spec/unit/hanami/logger_spec.rb, spec/unit/hanami/utils/basic_object_spec.rb, spec/unit/hanami/utils/deprecation_spec.rb, spec/unit/hanami/utils/escape_spec.rb
The lack of Hanami::Interactor::Result#is_a? causes my test suite to error in such examples:
```ruby
it { is_expected.to satisfy(&:failure?) }
```
=> Add instance_of?, is_a?, kind_of? To BasicObject

lib/hanami/utils/inflector.rb, spec/unit/hanami/utils/string_spec.rb
I'm super new to hanami and all its ecosystem, this PR is my naive approach at how I'd solve the problem of handling snake cased words which are part of the special singulars/plurals e.g. `control_exercises`.
Please give me some feedback and I'll be happy to apply to the best of my knowledge
fixes #339
=> Apply singular for snake_cased words

lib/hanami/utils/basic_object.rb, spec/unit/hanami/utils/basic_object_spec.rb
Ensure `Utils::BasicObject` to lookup constants at the top-level namespace, if they are missing in the current context.
Thanks to @jeremyevans for the suggestion: https://github.com/rtomayko/tilt/issues/347#issuecomment-534755061
=> Ensure `Utils::BasicObject` to lookup constants at the top-level namespace

.travis.yml
Reverts hanami/utils#341
TruffleRuby build keeps 16 minutes to complete and it's constantly failing. See an example: https://travis-ci.org/hanami/utils/jobs/589308192
This isn't a definitive NO to TruffleRuby. But for now it's just a waste of time and resources to keep it as it is in CI build.
/cc @davydovanton @deepj
=> Revert "Run specs in TruffleRuby in Travis CI"

lib/hanami/utils/files.rb, spec/unit/hanami/utils/files_spec.rb
`Utils::Files` ensure to properly append content when a file doesn't terminate with a newline
Closes #348
=> `Utils::Files.append` ensure to work without newline

Gemfile, lib/hanami/interactor.rb, lib/hanami/logger.rb, lib/hanami/utils.rb, lib/hanami/utils/basic_object.rb, lib/hanami/utils/blank.rb, lib/hanami/utils/callbacks.rb, lib/hanami/utils/escape.rb, lib/hanami/utils/file_list.rb, lib/hanami/utils/hash.rb, lib/hanami/utils/inflector.rb, lib/hanami/utils/json.rb, lib/hanami/utils/kernel.rb, lib/hanami/utils/load_paths.rb, lib/hanami/utils/query_string.rb, lib/hanami/utils/shell_color.rb, lib/hanami/utils/string.rb
I have noticed, different methods are using different approach to describe. The purpose ("to do smth") vs. the action ("does smth").
With this PR I tried to make it more consistent across the files.
=> API docs: unify documentation approach

.circleci/config.yml, .drone.yml, .travis.yml, Gemfile, lib/hanami/utils/files.rb, lib/hanami/utils/kernel.rb, spec/support/stdout.rb, spec/unit/hanami/utils/files_spec.rb
Hey.
I use `hanami-reloader` but I got the below error messages.
```
undefined method `end_with?' for nil:NilClass
/Users/ippachi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hanami-utils-1.3.5/lib/hanami/utils/files.rb:166:in `append'
/Users/ippachi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hanami-reloader-0.2.1/lib/hanami/reloader/cli.rb:16:in `call'
/Users/ippachi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hanami-1.3.3/lib/hanami/cli/commands/command.rb:85:in `call'
/Users/ippachi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hanami-cli-0.3.1/lib/hanami/cli.rb:57:in `call'
/Users/ippachi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hanami-1.3.3/bin/hanami:6:in `<top (required)>'
/Users/ippachi/.rbenv/versions/2.6.5/bin/hanami:23:in `load' …
```
=> Don't check breakline if file is empty.

lib/hanami/logger/filter.rb, spec/unit/hanami/logger_spec.rb
Currently, the `Logger` support filter only for a single hash. In case the input sent to the logger is an array of hash, the input does not filter as expected.
Before:
- Input
```ruby
[{:password=>"foo", :user=>{:name=>"foo", :password=>"abc"}}, {:password=>"bar", :user=>{:name=>"bar", :password=>"xyz"}}]
```
- Output
```ruby
[{:password=>"foo", :user=>{:name=>"foo", :password=>"abc"}}, {:password=>"bar", :user=>{:name=>"bar", :password=>"xyz"}}]
```
After:
- Input
```ruby
[{:password=>"foo", :user=>{:name=>"foo", :password=>"abc"}}, {:password=>"bar", :user=>{:name=>"bar", :password=>"xyz"}}]
```
- Output
```ruby
[{:password=>"foo", :user=>{:name=>"foo", :password=>"[FILTERED]"}}, {:password=>"bar", :user=>{:name=>"bar", :password=>"[FILTERED]"}}
```
=> Allows Logger can filter an array of hash

hanami-utils.gemspec, lib/hanami/utils/hash.rb, lib/hanami/utils/string.rb
Hi, I was looking at the **Utils::Hash** class in the `unstable` branch and noticed that they are using the gem "transport" that was archived and is now "dry-transformer".
I checked the trello (Hanami 2.0) just in case and did not see any tasks planned for this change
I changed the gem and made some small changes to fit the gem Dry::Transformer.
=> Change archived gem "Transproc" for its successor "Dry::Transformer"

lib/hanami/interactor.rb, spec/unit/hanami/interactor_spec.rb
I have an interactor like this:
```ruby
class CreateUser
include Hanami::Interactor
def initialize(user_repo: UserRepository.new)
@user_repo = user_repo
end
def call(**params)
user_repo.create(params)
end
end
```
When upgrade to ruby 3, this interactor raises `ArgumentError: wrong number of arguments (given 1, expected 0)` when initialized.
=> Allow keyword arguments in interactor initializer for ruby 3

lib/hanami/logger.rb, spec/unit/hanami/logger_spec.rb
If the `stream` is set to `File::NULL`, `@logdev` will be `nil`
This is due to the following logic in `Logger#initialize`
https://github.com/ruby/logger/blob/cdeddb2f6721e9003d71a7013d68733dd992b0d6/lib/logger.rb#L388-L394
The use case for this is if you wish to "throw away" any logs without
polluting stdout or a logfile. Perhaps in testing for instance where you might want `Hanami::Logger.new(stream: "/dev/null")`
=> `Hanami::Logger`: allow for to specify `File::NULL` as `stream:`

CHANGELOG.md, hanami-utils.gemspec, lib/hanami/utils/callbacks.rb, spec/unit/hanami/utils/callbacks_spec.rb
This is useful behavior on its own, but is also necessary to ensure callbacks from a base app-level Hanami::Action class propogate all the way through a slice-level base class to an individual action class.
This adds dry-core to the list of gem dependencies to get access to its easy-to-use `Dry::Equalizer`. This feels like a reasonable addition given that dry-core is already going to be in the bundle for any project using Hanami gems.
=> Make chains comparable by #== based on contents

.github/workflows/ci.yml, hanami-utils.gemspec, spec/unit/hanami/utils/deprecation_spec.rb, spec/unit/hanami/utils/kernel_spec.rb
We still get ostruct warnings but it's only used in a couple specs so I think we should rework the specs to not use OpenStruct... or we could just add it to the Gemfile because it's a _default_ gem. Which do you think is better? Feel free to make either change to this PR or defer to a future PR since it's just a warning.
Note that we have to add the dependency on bigdecimal because it's a _bundled_ gem, which means [it's installed with ruby but it can be removed by users](https://stdgems.org/). If users removed it, then our dependency is missing and this library breaks. So we have define it in the gemspec.
=> Add support for Ruby 3.4
